#!/bin/bash

STATUS=$(cat /sys/class/power_supply/BAT0/status)
BATT=$(cat /sys/class/power_supply/BAT0/capacity)

if [ "$STATUS" = "Discharging" ]; then
    if [ $BATT -ge 85 ]; then
        ICON=" "
    elif [ $BATT -ge 60 ]; then
	ICON=" "
    elif [ $BATT -ge 35 ]; then
	ICON=" "
    elif [ $BATT -ge 10 ]; then
	ICON=" "
    else 
	ICON=" "
    fi
fi

if [ "$STATUS" = "Charging" ]; then
   if [ $BATT -ge 85 ]; then
        ICON="⚡  "
    elif [ $BATT -ge 60 ]; then
        ICON="⚡  "
    elif [ $BATT -ge 35 ]; then
        ICON="⚡  "
    elif [ $BATT -ge 10 ]; then
        ICON="⚡  "
    else
        ICON="⚡  "
    fi
fi

echo " $ICON" "$BATT%"
